#TO_MODIFY
services:
  backend:
    container_name: iim_backend
    hostname: iim_backend
    build: ./backend
    ports: 
      - '4001:4001'
  mysql:
    container_name: iim_mysql
    hostname: iim_mysql
    image: mysql:8.0
    ports:
      - '3307:3306'
  frontend:
    container_name: iim_frontend
    hostname: iim_frontend
    build: ./frontend
    ports:
      - '4000:4000'